### ISSUE TITLE
Fix urdf2mjcf logic

### ISSUE THREAD

**Issue by budzianowski** [kscalelabs/urdf2mjcf#4]
Currently the package (https://github.com/kscalelabs/urdf2mjcf/) does not fully support xml from https://github.com/kscalelabs/sim/blob/master/sim/resources/gpr/robot_fixed.xml

1. Make sure that python urdf2mjcf/convert.py gpr.urdf --output gpr.xml will output identical file
2. Fix mujoco 2.3.6 vs latest issue (missing trunk with mass) - we should use latest mujoco
3. Bunch of discrepancies (visualgeom etc)

**Comment by alik-git** [comment]
gt file      sim/sim/resources/gpr/robot_fixed.xml
input file sim/resources/gpr/robot_fixed.urdf
